SMPLX_MOTION_ALIGN_CFG = {
    "gym_joint_names": ['L_Hip_x','L_Hip_y','L_Hip_z',
        'R_Hip_x','R_Hip_y','R_Hip_z',
        'Torso_x','Torso_y','Torso_z',
        'L_Knee_x','L_Knee_y','L_Knee_z',
        'R_Knee_x','R_Knee_y','R_Knee_z',
        'Spine_x','Spine_y','Spine_z',
        'L_Ankle_x','L_Ankle_y','L_Ankle_z',
        'R_Ankle_x','R_Ankle_y','R_Ankle_z',
        'Chest_x','Chest_y','Chest_z',
        'L_Toe_x','L_Toe_y','L_Toe_z',
        'R_Toe_x','R_Toe_y','R_Toe_z',
        'Neck_x','Neck_y','Neck_z',
        'L_Thorax_x','L_Thorax_y','L_Thorax_z',
        'R_Thorax_x','R_Thorax_y','R_Thorax_z',
        'Head_x','Head_y','Head_z',
        'L_Shoulder_x','L_Shoulder_y','L_Shoulder_z',
        'R_Shoulder_x','R_Shoulder_y','R_Shoulder_z',
        'L_Elbow_x','L_Elbow_y','L_Elbow_z',
        'R_Elbow_x','R_Elbow_y','R_Elbow_z',
        'L_Wrist_x','L_Wrist_y','L_Wrist_z',
        'R_Wrist_x','R_Wrist_y','R_Wrist_z',
        'L_Index1_x','L_Index1_y','L_Index1_z',
        'L_Middle1_x','L_Middle1_y','L_Middle1_z',
        'L_Pinky1_x','L_Pinky1_y','L_Pinky1_z',
        'L_Ring1_x','L_Ring1_y','L_Ring1_z',
        'L_Thumb1_x','L_Thumb1_y','L_Thumb1_z',
        'R_Index1_x','R_Index1_y','R_Index1_z',
        'R_Middle1_x','R_Middle1_y','R_Middle1_z',
        'R_Pinky1_x','R_Pinky1_y','R_Pinky1_z',
        'R_Ring1_x','R_Ring1_y','R_Ring1_z',
        'R_Thumb1_x','R_Thumb1_y','R_Thumb1_z',
        'L_Index2_x','L_Index2_y','L_Index2_z',
        'L_Middle2_x','L_Middle2_y','L_Middle2_z',
        'L_Pinky2_x','L_Pinky2_y','L_Pinky2_z',
        'L_Ring2_x','L_Ring2_y','L_Ring2_z',
        'L_Thumb2_x','L_Thumb2_y','L_Thumb2_z',
        'R_Index2_x','R_Index2_y','R_Index2_z',
        'R_Middle2_x','R_Middle2_y','R_Middle2_z',
        'R_Pinky2_x','R_Pinky2_y','R_Pinky2_z',
        'R_Ring2_x','R_Ring2_y','R_Ring2_z',
        'R_Thumb2_x','R_Thumb2_y','R_Thumb2_z',
        'L_Index3_x','L_Index3_y','L_Index3_z',
        'L_Middle3_x','L_Middle3_y','L_Middle3_z',
        'L_Pinky3_x','L_Pinky3_y','L_Pinky3_z',
        'L_Ring3_x','L_Ring3_y','L_Ring3_z',
        'L_Thumb3_x','L_Thumb3_y','L_Thumb3_z',
        'R_Index3_x','R_Index3_y','R_Index3_z',
        'R_Middle3_x','R_Middle3_y','R_Middle3_z',
        'R_Pinky3_x','R_Pinky3_y','R_Pinky3_z',
        'R_Ring3_x','R_Ring3_y','R_Ring3_z',
        'R_Thumb3_x','R_Thumb3_y','R_Thumb3_z'],
    "dof_body_ids": [i+1 for i in range(50)],
    "dof_offsets": [i for i in range(50)],
    "invalid_dof_id": [],
    "dof_indices_sim": [0],
    "dof_indices_motion": [0]
}
#     "gym_joint_names": [
#         "waist_joint",
#         "l_hip_roll_joint", "l_hip_pitch_joint", "l_thigh_joint",
#         "l_calf_joint",
#         "l_ankle_roll_joint", "l_ankle_pitch_joint",
#         "r_hip_roll_joint", "r_hip_pitch_joint", "r_thigh_joint",
#         "r_calf_joint",
#         "r_ankle_roll_joint", "r_ankle_pitch_joint",
#         "l_shoulder_roll_joint", "l_shoulder_pitch_joint", "l_upper_arm_joint",
#         "l_elbow_skip_1", "l_elbow_skip_2", "l_elbow_joint",
#         "l_wrist_joint",
#         "l_claw_joint",
#         "r_shoulder_roll_joint", "r_shoulder_pitch_joint", "r_upper_arm_joint",
#         "r_elbow_skip_1", "r_elbow_skip_2", "r_elbow_joint",
#         "r_wrist_joint",
#         "r_claw_joint",
#         "head_pitch_joint"
#     ],
#     "dof_body_ids": [1, 2, 3, 4, 5,  6,  7,  8,  9,  10,  11,  12,  13,  14,  15,  16],
#     "dof_offsets": [0, 1, 4, 5, 7, 10, 11, 13, 16, 19,  20,  21,  24,  27,  28,  29,  30],
#     "invalid_dof_id": [],
#     "dof_indices_sim": [0],
#     "dof_indices_motion": [0]
# }
